spring.application.name=expensight

# Railway Port
server.port=${PORT:8085}

# MySQL (Railway)
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false

# SQL Initialization
spring.sql.init.mode=never

# Optional Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect